spring:
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
      datasource:
        db1: # 数据源1配置
          url: jdbc:mysql://47.102.203.94:3306/jk?serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2: # 数据源2配置
          url: jdbc:mysql://47.102.203.94:3306/jk?serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  #mybatis
mybatis-plus:
  mapperLocations: classpath:mybatis/*.xml
  typeAliasesPackage: com.zhu.spring.springdemo.entity